# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Raaga' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Raaga

    pod 'Kingfisher'
    pod 'lottie-ios'

  target 'RaagaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
